language: node_js
sudo: false

node_js:
  - "0.10"
  - "0.12"
  - "5.1"
  - "5.2"

before_script:
  - mkdir -p gnatsd
  - wget https://github.com/nats-io/gnatsd/releases/download/v0.7.2/gnatsd-v0.7.2-linux-amd64.tar.gz -qO - | tar -zxvC gnatsd/
