language: node_js
sudo: false

node_js:
  - "4"
  - "6"
  - "8"
  - "9"

git:
  depth: false

env:
  - NATS_VERSION=v1.0.6

before_script:
  - wget "https://github.com/nats-io/gnatsd/releases/download/$NATS_VERSION/gnatsd-$NATS_VERSION-linux-amd64.zip" -O tmp.zip
  - unzip tmp.zip
  - mv gnatsd-$NATS_VERSION-linux-amd64 gnatsd

script:
  - if [[ "$TRAVIS_NODE_VERSION" == 4 ]]; then npm test; fi
  - if [[ "$TRAVIS_NODE_VERSION" == 6 ]]; then npm test; fi
  - if [[ "$TRAVIS_NODE_VERSION" == 8 ]]; then npm test; fi
  - if [[ "$TRAVIS_NODE_VERSION" == 9 ]]; then npm run coveralls; fi