name: NATS.js CI

on:
  push:
    tags:
      - '*'
    branches:
      - '*'
  pull_request:
    branches: [main]

jobs:
  test:
    strategy:
      matrix:
        node-version: [20.x, 19.x, 18.x, 16.x]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout NATS.js
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Use Deno Version ${{ matrix.deno-version }}
        uses: denoland/setup-deno@v1.1.1
        with:
          deno-version: 1.30.3
      - name: Set NATS Server Version
        run: echo "NATS_VERSION=v2.9.17" >> $GITHUB_ENV
      - name: Get nats-server
        run: |
          wget "https://github.com/nats-io/nats-server/releases/download/$NATS_VERSION/nats-server-$NATS_VERSION-linux-amd64.zip" -O tmp.zip
          unzip tmp.zip
          mv nats-server-$NATS_VERSION-linux-amd64 nats-server
      - run: npm ci
      - run: npm run prepack
      - run: npm test
        env:
          CI: true
      - name: Gather coverage
        if: matrix.node-version == '18.x'
        run: npm run coveralls
      - name: Upload coverage
        uses: coverallsapp/github-action@1.1.3
        if: matrix.node-version == '18.x'
        with:
          github-token: ${{ secrets.github_token }}
          path-to-lcov: ./coverage/lcov.info
